/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import javax.swing.ImageIcon;
import app.Manage;
import java.awt.Cursor;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Luisa María Ortiz
 */
public class Admin extends javax.swing.JFrame {
Manage manager;
DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyy HH:mm:ss");
boolean arbol=false;
    
    public Admin(Manage manage) {
        ImageIcon img = new ImageIcon("src\\interfaz\\Img\\iconv.png");
        this.setIconImage(img.getImage());
        this.manager=manage;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton_cerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Button_CargaClientes = new javax.swing.JButton();
        jLabel_arbol = new javax.swing.JLabel();
        jLabel_time = new javax.swing.JLabel();
        jButton_verClientes = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");
        setLocation(new java.awt.Point(15, 10));
        setName("Administrador"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAlignmentX(10.0F);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Administrador");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jButton_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Img/exit_opt.png"))); // NOI18N
        jButton_cerrar.setToolTipText("Cerrar sesión");
        jButton_cerrar.setBorder(null);
        jButton_cerrar.setBorderPainted(false);
        jButton_cerrar.setPreferredSize(new java.awt.Dimension(96, 40));
        jButton_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cerrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 40, 40, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Img/banneradmin.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 100));

        Button_CargaClientes.setBackground(new java.awt.Color(51, 0, 51));
        Button_CargaClientes.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Button_CargaClientes.setForeground(new java.awt.Color(255, 255, 255));
        Button_CargaClientes.setText("Cargar Clientes");
        Button_CargaClientes.setBorder(null);
        Button_CargaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CargaClientesActionPerformed(evt);
            }
        });
        jPanel1.add(Button_CargaClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, 40));

        jLabel_arbol.setToolTipText("Click si el gráfico no se ve completo.");
        jLabel_arbol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel_arbol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_arbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_arbolMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel_arbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 690, 440));

        jLabel_time.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_time.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_time.setText("Última actualización de árbol: null ");
        jPanel1.add(jLabel_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 620, -1, -1));

        jButton_verClientes.setBackground(new java.awt.Color(0, 51, 102));
        jButton_verClientes.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButton_verClientes.setForeground(new java.awt.Color(255, 255, 255));
        jButton_verClientes.setText("Ver árbol de clientes");
        jButton_verClientes.setBorder(null);
        jButton_verClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_verClientesActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_verClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1312, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cerrarActionPerformed
        Login login = new Login(this.manager);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_cerrarActionPerformed

    private void Button_CargaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CargaClientesActionPerformed
        JFileChooser chooser = new JFileChooser();
         
         FileNameExtensionFilter filter = new FileNameExtensionFilter("JSON", "json");
         chooser.setFileFilter(filter);
        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
         File fichero = chooser.getSelectedFile();
        this.manager.cargaMasiva(fichero);
        }
       
    }//GEN-LAST:event_Button_CargaClientesActionPerformed

    private void jButton_verClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_verClientesActionPerformed
        
             try {
                manager.graficarClientes();
                Thread.sleep(1000);
                this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
                this.arbol=true;

       } catch (InterruptedException e) {

         
       }
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        ImageIcon img = new ImageIcon("Reportes de Administrador\\Clientes.png");
        this.jLabel_arbol.setIcon(img);
        this.jLabel_time.setText("Última actualización de árbol: "+this.dtf.format(LocalDateTime.now()));
    }//GEN-LAST:event_jButton_verClientesActionPerformed

    private void jLabel_arbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_arbolMouseClicked
        if(this.arbol){
             try {

            File file = new File ("Reportes de Administrador\\Clientes.png");
            Desktop.getDesktop().open(file);

     }catch (IOException ex) {System.out.println(ex);}

        }
    }//GEN-LAST:event_jLabel_arbolMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_CargaClientes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_cerrar;
    private javax.swing.JButton jButton_verClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_arbol;
    private javax.swing.JLabel jLabel_time;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
