
package interfaz;

import app.Manage;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Luisa María Ortiz
 */
public class Registro extends javax.swing.JFrame {
Manage manager;
    /**
     * Creates new form Registro
     */
    public Registro(Manage manager) {
        this.manager=manager;
        ImageIcon img = new ImageIcon("src\\interfaz\\Img\\iconv.png");
        this.setIconImage(img.getImage());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_Regresar = new javax.swing.JButton();
        jTextField_nombre = new javax.swing.JTextField();
        jTextField_dpi = new javax.swing.JTextField();
        jTextField_password = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton_Registrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");
        setLocation(new java.awt.Point(240, 120));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/Img/bgregistrof.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 270, 450));

        jButton_Regresar.setBackground(new java.awt.Color(255, 255, 0));
        jButton_Regresar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButton_Regresar.setForeground(new java.awt.Color(0, 0, 0));
        jButton_Regresar.setText("Regresar");
        jButton_Regresar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegresarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 30));

        jTextField_nombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextField_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nombreActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 410, 40));

        jTextField_dpi.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel1.add(jTextField_dpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 410, 40));

        jTextField_password.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel1.add(jTextField_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 410, 40));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Nombre Completo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("DPI");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jButton_Registrar.setBackground(new java.awt.Color(0, 204, 0));
        jButton_Registrar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButton_Registrar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Registrar.setText("Registrar");
        jButton_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 130, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("*");
        jLabel5.setToolTipText("Obligatorio");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 10, 20));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("*");
        jLabel6.setToolTipText("Obligatorio");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 10, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("*");
        jLabel7.setToolTipText("Obligatorio");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 10, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegresarActionPerformed
        Login login = new Login(this.manager);
            login.setVisible(true);
            this.dispose();
        
    }//GEN-LAST:event_jButton_RegresarActionPerformed

    private void jTextField_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nombreActionPerformed

    private void jButton_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrarActionPerformed
        String nombre = this.jTextField_nombre.getText();
        String password = this.jTextField_password.getText();
        long dpi;
        try{
        dpi = Long.valueOf(this.jTextField_dpi.getText());
        }catch(NumberFormatException e){JOptionPane.showMessageDialog(null, "Ingrese un DPI válido", "Advertencia", JOptionPane.ERROR_MESSAGE);
        dpi=0;
                return;
                
        }
        if(dpi>0){
            if(nombre.equals("") || password.equals("")){
               JOptionPane.showMessageDialog(null, "Debe llenar todos los campos", "Advertencia", JOptionPane.ERROR_MESSAGE); 
            }
            else{
        if(manager.registrar(nombre, password, dpi)){
             JOptionPane.showMessageDialog(null, "¡Registro exitoso!", "Notificación", JOptionPane.INFORMATION_MESSAGE);
             Login login = new Login(this.manager);
            login.setVisible(true);
            this.dispose();
        }
        else{
            this.jTextField_dpi.setText("");
            this.jTextField_nombre.setText("");
            this.jTextField_password.setText("");
        }
            }
    }
    }//GEN-LAST:event_jButton_RegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Registrar;
    private javax.swing.JButton jButton_Regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_dpi;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JTextField jTextField_password;
    // End of variables declaration//GEN-END:variables
}
